[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "arabicreshaper"
version = "1.0.1"
description = "Reshape Arabic text for proper display"

[tool.setuptools.packages.find]
where = ["."]
include = ["arabicreshaper*"]

[tool.setuptools.package-data]
arabicreshaper = ["ArabicShaping.txt"]